# Intro 
- Tensorflow =  tensor + flow 
- Tensor = matrixs in general forms (1D (dimension),2D...N-D of data sets)
- flow   = data pipeline 

 ##### Via the linear computation pipeline of tensors, A deep learning model can be built 

Similiar as Numpy, Tensorflow using matrix ways dealing with data procrocess. The thing should be noticed is :  every element/variable/method should be declared via Tensorflow method first then  they can be implemented in Tensorflow workflow.

- e.g. x =  tf.constant(1)


# Basic objects  

    - Constant 
    - Variable 
    - Session
    - Tensor
    - Placeholder 
    - Activation 
    
# Basic framework of ML model 
  ##### Y = a*X + b 
  - X = input  
  - a = slope
  - b = intercept
  - Y = prediction output 
  

In [2]:
# import analysis library
import pandas as pd, numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline
%pylab inline
plt.style.use('ggplot')

import tensorflow as tf

Populating the interactive namespace from numpy and matplotlib


## 1) Constant 

In [9]:
a = tf.constant(42)
b = tf.constant(2)
c = tf.constant([1,2,3])

In [11]:
a

<tf.Tensor 'Const_3:0' shape=() dtype=int32>

In [10]:
c

<tf.Tensor 'Const_5:0' shape=(3,) dtype=int32>

In [8]:
type(a)

tensorflow.python.framework.ops.Tensor

## 2) Variable

In [12]:
x = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0))

In [13]:
x

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32_ref>

In [14]:
type(x)

tensorflow.python.ops.variables.Variable

## 3) Session

- A object that make elements in Tensowflow are executed
- 2 ways run session


In [26]:
a = tf.constant(42)
b = tf.constant(2)

In [16]:
# 1st way run session 
sess = tf.Session()
print(sess.run(a))

42


In [17]:
print(sess.run(a+b))

44


In [20]:
# 2nd  way run session 

with tf.Session() as sess:
    sess.run(a)
    print (sess.run(a))
    # to release the resources if session is no longer used  
    sess.close()

42


## 4) Tensor 

In [41]:
# more constant (tensor) demo 

# fixed tenfors 
zero_tsr = tf.zeros([2, 5])
ones_tsr = tf.ones([3, 3])
filled_tsr = tf.fill([4, 4], 42)
constant_tsr = tf.constant([1,2,3])


# initialize variables based on the shape of other tensors
zeros_similar = tf.zeros_like(constant_tsr)

In [42]:
print(sess.run(zero_tsr))
print ('')
print(sess.run(ones_tsr))
print ('')
print(sess.run(filled_tsr))
print ('')
print(sess.run(constant_tsr))
print ('')
print(sess.run(zeros_similar))

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]]

[1 2 3]

[0 0 0]


In [65]:
# similar as Numpy, Tensorflow support defined intervals tensors 

# linspace 
linear_tsr = tf.linspace(10.0, 12.0, 3, name="linspace")
linear_tsr2 = tf.linspace(10.0, 12.0, 10, name="linspace")
# range 
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)
# random 
randunif_tsr = tf.random_uniform([2, 3],minval=0, maxval=1)
# random normal distribution 
randnorm_tsr = tf.random_normal([2, 3],mean=0.0, stddev=1.0)
# random normal distribution  with certain bound 
runcnorm_tsr2 = tf.truncated_normal([2, 3], mean=0.0, stddev=1.0)

In [66]:
print(sess.run(linear_tsr))
print ('')
print(sess.run(linear_tsr2))
print ('')
print(sess.run(integer_seq_tsr))
print ('')
print(sess.run(randunif_tsr))
print ('')
print(sess.run(randnorm_tsr))
print ('')
print(sess.run(runcnorm_tsr2))
print ('')

[ 10.  11.  12.]

[ 10.          10.22222233  10.44444466  10.66666698  10.88888931
  11.11111069  11.33333302  11.55555534  11.77777767  12.        ]

[ 6  9 12]

[[ 0.41237617  0.93409348  0.64434648]
 [ 0.79733586  0.49604332  0.96494699]]

[[ 1.87211275  1.12922251 -1.56717575]
 [-0.14216419 -0.90267384  1.11291623]]

[[ 1.25072265 -0.44186497  1.17872536]
 [ 0.31544462  0.00555641 -0.04740591]]



## 5) Placeholder
- Placeholders is the object that allow you to feed in
  data of a specific type and shape and depend on the results of the 
  computational graph, such as the expected outcome of a computation.

In [106]:
# placeholder
x1 = tf.placeholder(tf.float32, shape=(3, 3))

# tf.matmul : x1 * x1 
y1 = tf.matmul(x1, x1)

# tf.matmul : y = tf.identity(x1), => y = x1 
y = tf.identity(x1)

In [105]:
rand_array = np.random.rand(3, 3)

print(sess.run(y1, feed_dict={x1: rand_array}))
print ('')
print(sess.run(y, feed_dict={x1: rand_array}))

[[ 0.67195678  1.75412583  0.95771956]
 [ 0.65319479  1.65666497  0.86883068]
 [ 0.1403054   1.44914865  1.4819591 ]]

[[ 0.06807726  0.94154024  0.93124032]
 [ 0.0755524   0.8373245   0.91343814]
 [ 0.64020705  0.9682287   0.036816  ]]


In [110]:
# p. 9 
# to be finished ... 